// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/media_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/media_repository.go -destination=internal/usecase/mocks/mock_media_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "sense-backend/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaRepository is a mock of MediaRepository interface.
type MockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaRepositoryMockRecorder is the mock recorder for MockMediaRepository.
type MockMediaRepositoryMockRecorder struct {
	mock *MockMediaRepository
}

// NewMockMediaRepository creates a new mock instance.
func NewMockMediaRepository(ctrl *gomock.Controller) *MockMediaRepository {
	mock := &MockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepository) EXPECT() *MockMediaRepositoryMockRecorder {
	return m.recorder
}

// CheckOwnership mocks base method.
func (m *MockMediaRepository) CheckOwnership(ctx context.Context, mediaID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOwnership", ctx, mediaID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOwnership indicates an expected call of CheckOwnership.
func (mr *MockMediaRepositoryMockRecorder) CheckOwnership(ctx, mediaID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOwnership", reflect.TypeOf((*MockMediaRepository)(nil).CheckOwnership), ctx, mediaID, userID)
}

// Create mocks base method.
func (m *MockMediaRepository) Create(ctx context.Context, media *domain.MediaAsset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMediaRepositoryMockRecorder) Create(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMediaRepository)(nil).Create), ctx, media)
}

// Delete mocks base method.
func (m *MockMediaRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMediaRepository) GetByID(ctx context.Context, id string) (*domain.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaRepository)(nil).GetByID), ctx, id)
}

// GetByOwner mocks base method.
func (m *MockMediaRepository) GetByOwner(ctx context.Context, ownerID string, limit, offset int) ([]*domain.MediaAsset, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerID, limit, offset)
	ret0, _ := ret[0].([]*domain.MediaAsset)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockMediaRepositoryMockRecorder) GetByOwner(ctx, ownerID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockMediaRepository)(nil).GetByOwner), ctx, ownerID, limit, offset)
}
