// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/recommendation_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/recommendation_repository.go -destination=internal/usecase/mocks/mock_recommendation_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "sense-backend/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRecommendationRepository is a mock of RecommendationRepository interface.
type MockRecommendationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationRepositoryMockRecorder
	isgomock struct{}
}

// MockRecommendationRepositoryMockRecorder is the mock recorder for MockRecommendationRepository.
type MockRecommendationRepositoryMockRecorder struct {
	mock *MockRecommendationRepository
}

// NewMockRecommendationRepository creates a new mock instance.
func NewMockRecommendationRepository(ctrl *gomock.Controller) *MockRecommendationRepository {
	mock := &MockRecommendationRepository{ctrl: ctrl}
	mock.recorder = &MockRecommendationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationRepository) EXPECT() *MockRecommendationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecommendationRepository) Create(ctx context.Context, recommendation *domain.Recommendation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, recommendation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecommendationRepositoryMockRecorder) Create(ctx, recommendation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecommendationRepository)(nil).Create), ctx, recommendation)
}

// GetByUser mocks base method.
func (m *MockRecommendationRepository) GetByUser(ctx context.Context, userID string, limit, offset int) ([]*domain.Recommendation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Recommendation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockRecommendationRepositoryMockRecorder) GetByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockRecommendationRepository)(nil).GetByUser), ctx, userID, limit, offset)
}

// GetPublicationIDs mocks base method.
func (m *MockRecommendationRepository) GetPublicationIDs(ctx context.Context, userID string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicationIDs", ctx, userID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicationIDs indicates an expected call of GetPublicationIDs.
func (mr *MockRecommendationRepositoryMockRecorder) GetPublicationIDs(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicationIDs", reflect.TypeOf((*MockRecommendationRepository)(nil).GetPublicationIDs), ctx, userID, limit)
}

// Hide mocks base method.
func (m *MockRecommendationRepository) Hide(ctx context.Context, recommendationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hide", ctx, recommendationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Hide indicates an expected call of Hide.
func (mr *MockRecommendationRepositoryMockRecorder) Hide(ctx, recommendationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hide", reflect.TypeOf((*MockRecommendationRepository)(nil).Hide), ctx, recommendationID)
}
