// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/tag_repository.go -destination=internal/usecase/mocks/mock_tag_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "sense-backend/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// AttachToPublication mocks base method.
func (m *MockTagRepository) AttachToPublication(ctx context.Context, publicationID, tagID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachToPublication", ctx, publicationID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachToPublication indicates an expected call of AttachToPublication.
func (mr *MockTagRepositoryMockRecorder) AttachToPublication(ctx, publicationID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachToPublication", reflect.TypeOf((*MockTagRepository)(nil).AttachToPublication), ctx, publicationID, tagID)
}

// Create mocks base method.
func (m *MockTagRepository) Create(ctx context.Context, tag *domain.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), ctx, tag)
}

// DetachFromPublication mocks base method.
func (m *MockTagRepository) DetachFromPublication(ctx context.Context, publicationID, tagID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachFromPublication", ctx, publicationID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachFromPublication indicates an expected call of DetachFromPublication.
func (mr *MockTagRepositoryMockRecorder) DetachFromPublication(ctx, publicationID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachFromPublication", reflect.TypeOf((*MockTagRepository)(nil).DetachFromPublication), ctx, publicationID, tagID)
}

// GetByID mocks base method.
func (m *MockTagRepository) GetByID(ctx context.Context, id string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockTagRepository) GetByName(ctx context.Context, name string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTagRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTagRepository)(nil).GetByName), ctx, name)
}

// GetByPublication mocks base method.
func (m *MockTagRepository) GetByPublication(ctx context.Context, publicationID string) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPublication", ctx, publicationID)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPublication indicates an expected call of GetByPublication.
func (mr *MockTagRepositoryMockRecorder) GetByPublication(ctx, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPublication", reflect.TypeOf((*MockTagRepository)(nil).GetByPublication), ctx, publicationID)
}

// GetPopular mocks base method.
func (m *MockTagRepository) GetPopular(ctx context.Context, limit int, search *string) ([]*domain.Tag, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopular", ctx, limit, search)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPopular indicates an expected call of GetPopular.
func (mr *MockTagRepositoryMockRecorder) GetPopular(ctx, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopular", reflect.TypeOf((*MockTagRepository)(nil).GetPopular), ctx, limit, search)
}
