// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/publication_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/publication_repository.go -destination=internal/usecase/mocks/mock_publication_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "sense-backend/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPublicationRepository is a mock of PublicationRepository interface.
type MockPublicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPublicationRepositoryMockRecorder
	isgomock struct{}
}

// MockPublicationRepositoryMockRecorder is the mock recorder for MockPublicationRepository.
type MockPublicationRepositoryMockRecorder struct {
	mock *MockPublicationRepository
}

// NewMockPublicationRepository creates a new mock instance.
func NewMockPublicationRepository(ctrl *gomock.Controller) *MockPublicationRepository {
	mock := &MockPublicationRepository{ctrl: ctrl}
	mock.recorder = &MockPublicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicationRepository) EXPECT() *MockPublicationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicationRepository) Create(ctx context.Context, publication *domain.Publication, mediaIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, publication, mediaIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPublicationRepositoryMockRecorder) Create(ctx, publication, mediaIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicationRepository)(nil).Create), ctx, publication, mediaIDs)
}

// Delete mocks base method.
func (m *MockPublicationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicationRepository)(nil).Delete), ctx, id)
}

// GetByAuthor mocks base method.
func (m *MockPublicationRepository) GetByAuthor(ctx context.Context, authorID string, viewerUserID *string, filters *domain.PublicationFilters, limit, offset int) ([]*domain.PublicationWithLikeStatus, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuthor", ctx, authorID, viewerUserID, filters, limit, offset)
	ret0, _ := ret[0].([]*domain.PublicationWithLikeStatus)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAuthor indicates an expected call of GetByAuthor.
func (mr *MockPublicationRepositoryMockRecorder) GetByAuthor(ctx, authorID, viewerUserID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuthor", reflect.TypeOf((*MockPublicationRepository)(nil).GetByAuthor), ctx, authorID, viewerUserID, filters, limit, offset)
}

// GetByID mocks base method.
func (m *MockPublicationRepository) GetByID(ctx context.Context, id string) (*domain.Publication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Publication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPublicationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPublicationRepository)(nil).GetByID), ctx, id)
}

// GetByIDWithLikeStatus mocks base method.
func (m *MockPublicationRepository) GetByIDWithLikeStatus(ctx context.Context, id string, viewerUserID *string) (*domain.PublicationWithLikeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithLikeStatus", ctx, id, viewerUserID)
	ret0, _ := ret[0].(*domain.PublicationWithLikeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithLikeStatus indicates an expected call of GetByIDWithLikeStatus.
func (mr *MockPublicationRepositoryMockRecorder) GetByIDWithLikeStatus(ctx, id, viewerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithLikeStatus", reflect.TypeOf((*MockPublicationRepository)(nil).GetByIDWithLikeStatus), ctx, id, viewerUserID)
}

// GetFeed mocks base method.
func (m *MockPublicationRepository) GetFeed(ctx context.Context, userID *string, filters *domain.FeedFilters, limit, offset int) ([]*domain.PublicationWithLikeStatus, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, userID, filters, limit, offset)
	ret0, _ := ret[0].([]*domain.PublicationWithLikeStatus)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockPublicationRepositoryMockRecorder) GetFeed(ctx, userID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockPublicationRepository)(nil).GetFeed), ctx, userID, filters, limit, offset)
}

// GetLikedUsers mocks base method.
func (m *MockPublicationRepository) GetLikedUsers(ctx context.Context, publicationID string, limit, offset int) ([]*domain.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedUsers", ctx, publicationID, limit, offset)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLikedUsers indicates an expected call of GetLikedUsers.
func (mr *MockPublicationRepositoryMockRecorder) GetLikedUsers(ctx, publicationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedUsers", reflect.TypeOf((*MockPublicationRepository)(nil).GetLikedUsers), ctx, publicationID, limit, offset)
}

// GetLikesCount mocks base method.
func (m *MockPublicationRepository) GetLikesCount(ctx context.Context, publicationID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesCount", ctx, publicationID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikesCount indicates an expected call of GetLikesCount.
func (mr *MockPublicationRepositoryMockRecorder) GetLikesCount(ctx, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesCount", reflect.TypeOf((*MockPublicationRepository)(nil).GetLikesCount), ctx, publicationID)
}

// GetMediaIDs mocks base method.
func (m *MockPublicationRepository) GetMediaIDs(ctx context.Context, publicationID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaIDs", ctx, publicationID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaIDs indicates an expected call of GetMediaIDs.
func (mr *MockPublicationRepositoryMockRecorder) GetMediaIDs(ctx, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaIDs", reflect.TypeOf((*MockPublicationRepository)(nil).GetMediaIDs), ctx, publicationID)
}

// GetSaved mocks base method.
func (m *MockPublicationRepository) GetSaved(ctx context.Context, userID string, filters *domain.PublicationFilters, limit, offset int) ([]*domain.SavedPublicationWithLikeStatus, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaved", ctx, userID, filters, limit, offset)
	ret0, _ := ret[0].([]*domain.SavedPublicationWithLikeStatus)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSaved indicates an expected call of GetSaved.
func (mr *MockPublicationRepositoryMockRecorder) GetSaved(ctx, userID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaved", reflect.TypeOf((*MockPublicationRepository)(nil).GetSaved), ctx, userID, filters, limit, offset)
}

// IsLiked mocks base method.
func (m *MockPublicationRepository) IsLiked(ctx context.Context, userID, publicationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, userID, publicationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockPublicationRepositoryMockRecorder) IsLiked(ctx, userID, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockPublicationRepository)(nil).IsLiked), ctx, userID, publicationID)
}

// IsSaved mocks base method.
func (m *MockPublicationRepository) IsSaved(ctx context.Context, userID, publicationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSaved", ctx, userID, publicationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSaved indicates an expected call of IsSaved.
func (mr *MockPublicationRepositoryMockRecorder) IsSaved(ctx, userID, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSaved", reflect.TypeOf((*MockPublicationRepository)(nil).IsSaved), ctx, userID, publicationID)
}

// Like mocks base method.
func (m *MockPublicationRepository) Like(ctx context.Context, userID, publicationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, userID, publicationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Like indicates an expected call of Like.
func (mr *MockPublicationRepositoryMockRecorder) Like(ctx, userID, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockPublicationRepository)(nil).Like), ctx, userID, publicationID)
}

// Save mocks base method.
func (m *MockPublicationRepository) Save(ctx context.Context, userID, publicationID string, note *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, publicationID, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPublicationRepositoryMockRecorder) Save(ctx, userID, publicationID, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPublicationRepository)(nil).Save), ctx, userID, publicationID, note)
}

// Search mocks base method.
func (m *MockPublicationRepository) Search(ctx context.Context, query string, viewerUserID *string, filters *domain.SearchFilters, limit, offset int) ([]*domain.PublicationWithLikeStatus, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, viewerUserID, filters, limit, offset)
	ret0, _ := ret[0].([]*domain.PublicationWithLikeStatus)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockPublicationRepositoryMockRecorder) Search(ctx, query, viewerUserID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPublicationRepository)(nil).Search), ctx, query, viewerUserID, filters, limit, offset)
}

// Unsave mocks base method.
func (m *MockPublicationRepository) Unsave(ctx context.Context, userID, publicationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsave", ctx, userID, publicationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsave indicates an expected call of Unsave.
func (mr *MockPublicationRepositoryMockRecorder) Unsave(ctx, userID, publicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsave", reflect.TypeOf((*MockPublicationRepository)(nil).Unsave), ctx, userID, publicationID)
}

// Update mocks base method.
func (m *MockPublicationRepository) Update(ctx context.Context, publication *domain.Publication, mediaIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, publication, mediaIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPublicationRepositoryMockRecorder) Update(ctx, publication, mediaIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublicationRepository)(nil).Update), ctx, publication, mediaIDs)
}
