// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/ai/client_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/ai/client_interface.go -destination=internal/usecase/mocks/mock_ai_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	ai "sense-backend/internal/infrastructure/ai"

	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Compose mocks base method.
func (m *MockClientInterface) Compose(ctx context.Context, req *ai.ComposeRequest) (*ai.ComposeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compose", ctx, req)
	ret0, _ := ret[0].(*ai.ComposeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compose indicates an expected call of Compose.
func (mr *MockClientInterfaceMockRecorder) Compose(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compose", reflect.TypeOf((*MockClientInterface)(nil).Compose), ctx, req)
}

// HealthCheck mocks base method.
func (m *MockClientInterface) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockClientInterfaceMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockClientInterface)(nil).HealthCheck), ctx)
}

// Recommend mocks base method.
func (m *MockClientInterface) Recommend(ctx context.Context, userID string) (*ai.RecommendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommend", ctx, userID)
	ret0, _ := ret[0].(*ai.RecommendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockClientInterfaceMockRecorder) Recommend(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockClientInterface)(nil).Recommend), ctx, userID)
}
